# Generated by Django 4.1.2 on 2022-11-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('info', models.TextField()),
                ('image', models.ImageField(upload_to='teachers_image')),
                ('name_of_teacher', models.CharField(max_length=35)),
            ],
        ),
    ]
