# Generated by Django 4.1.2 on 2022-11-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('info', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='info',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='title',
        ),
    ]
