# Generated by Django 4.1.2 on 2022-11-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_info_teachers_remove_teachers_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind_of_vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles_image')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles_Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name_of_vehicles', models.CharField(max_length=38)),
                ('description', models.TextField()),
            ],
        ),
    ]
