# Generated by Django 4.1.2 on 2022-11-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_kind_of_vehicles_vehicles_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
