# Generated by Django 4.1.2 on 2022-11-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_info_student_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_student',
            name='image',
            field=models.ImageField(default='exit', upload_to=''),
            preserve_default=False,
        ),
    ]
