# Generated by Django 4.1.2 on 2022-11-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_message_remove_contact_email_remove_contact_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
